### ISSUE TITLE
problem with running ISEScan stats

### ISSUE THREAD

**Issue by gaworj** [AhmedElsherbini/ISEScan_stats#1]
Hi,

I tried to run:

ISEScan_stats/ise_stats_with_nis.py -i input_data/ -p ISEscan_summary

and the script shows me this error

Traceback (most recent call last):
  File "ISEScan_stats/ise_stats_with_nis.py", line 62, in <module>
    df1["Isolate"] = df["filename"].str.removesuffix(".fna.sum")
AttributeError: 'StringMethods' object has no attribute 'removesuffix

I'm using Ubuntu 16.04 and python 3.7. All of the sugeested packages were installed in my conda env.

Any hints?

Bests,
Jan

**Comment by gaworj** [comment]
Haha! I have created new conda env with python 3.9 + suggested python packages and the scripts works smoothly!

Please add neccessary info to your manual.

Bests,
Jan

PS. Can you also add option for exporting to tab separated file? Excel format is nice but simple tabulated file will be also helpful.

**Comment by AhmedElsherbini** [comment]
Hi Jan,

I am happy that the script worked with you,

Thank you for your observation.

Indeed, now, I  added the info regarding the need for Python 3.9. and  I moved to CSV instead of Excel.

Anyhow, you can try it now, and do not forget to star the repo, if it is useful for your work :sweat_smile: .

Best,
Ahmed
